// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyZWd1jHUX5caAYbrbpE2PxNcWOawMBQM',
    appId: '1:848795854304:web:33a629e67208941ad4b785',
    messagingSenderId: '848795854304',
    projectId: 'social-media-73f64',
    authDomain: 'social-media-73f64.firebaseapp.com',
    storageBucket: 'social-media-73f64.appspot.com',
    measurementId: 'G-DDS2BTCTDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3qbv0cPVa_Tf7iS6DZ2stuTXfQh9YpA',
    appId: '1:848795854304:android:8573b8dfa0bcfcb0d4b785',
    messagingSenderId: '848795854304',
    projectId: 'social-media-73f64',
    storageBucket: 'social-media-73f64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk0_XMwvK5iHnG8EsSdOYPxYSCi7x5qGU',
    appId: '1:848795854304:ios:02826fca086bd936d4b785',
    messagingSenderId: '848795854304',
    projectId: 'social-media-73f64',
    storageBucket: 'social-media-73f64.appspot.com',
    iosBundleId: 'com.rec.socialmedia.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk0_XMwvK5iHnG8EsSdOYPxYSCi7x5qGU',
    appId: '1:848795854304:ios:9818a7b68de0435ed4b785',
    messagingSenderId: '848795854304',
    projectId: 'social-media-73f64',
    storageBucket: 'social-media-73f64.appspot.com',
    iosBundleId: 'com.rec.socialmedia.socialMedia.RunnerTests',
  );
}
